### ISSUE TITLE
Support for radios that produce samples > 16 bit

### ISSUE THREAD

**Issue by amontefusco** [f4exb/sdrdaemon#8]
In my understanding the sample size is at the moment fixed to 16 bit.
Thats a pity, as several radio have more bit. Do you think to relaxe that constraint in the future ?

**Comment by f4exb** [comment]
Well at the moment none of these radios are supported. Airspy, BladeRF, HackRF and RTL-SDR are all <16 bits. For the moment transferring signed shorts for all devices has the advantage of simplicity and is moderately demanding on the network traffic rate. There is a decimation with bit gain that takes place that in some instances may allow to transmit a few more bits than 16 but I thought it is just not worth it.

**Comment by f4exb** [comment]
With new hardware like Airspy HF+ and also good old Perseus that use 16 bit or more samples this could be indeed interesting. But this should only be an option for compatible hardware not to compromise fast lightweight processing advantage of 16 bit processing when only 16 bit precision is needed or lightweight processing is desired. This should also be implemented in SDRangel. I am thinking of it but work on higher priority features for the moment.

**Comment by amontefusco** [comment]
Ok, let me know if and when you decide to proceed. I have a lot of radios that spit out 24 bit signed or floating point +1.0/-1.0 I/Q samples (Perseus, S1, Hermes, Mercury, QS1R), so I could help in the driver/plugins part.

**Comment by f4exb** [comment]
This change is already going on in SDRangel: https://github.com/f4exb/sdrangel/issues/128 There will soon be a need to feed in 24 bit samples from SDRdaemon so it is getting closer.

SDRangel will use 32 bit integers internally normalized to 24 bit but for travelling over the network some kind of space optimization might be handy. Instead of trying to send 3 bytes samples one after the other one could send groups of 4 samples with 3 samples "horizontal" and one "vertical". Thus 3 int32 will actually send 4 samples or 2 I/Q samples. This could make stream conversion to 32 bit simpler.

I think I will get a Perseus myself but I am interested in help with the other hardware you mention.

**Comment by jboone** [comment]
@f4exb I started work on libairspyhf support here: https://github.com/jboone/sdrdaemon/tree/airspyhf

...and ran in to this sample type issue. Interestingly, the internals of libairspyhf show a conversion from int16s to float:

https://github.com/airspy/airspyhf/blob/7ea3edf07a30e524e300dd99e1d8cef040beac55/libairspyhf/src/airspyhf.c#L357

That conversion function does a lot of things:

https://github.com/airspy/airspyhf/blob/7ea3edf07a30e524e300dd99e1d8cef040beac55/libairspyhf/src/airspyhf.c#L290

With SDRAngel as the consumer, all those operations seem redundant. I have the impression SDRAngel already does its own normalizing, frequency translation, and IQ balancing.

I think I should propose to the libairsphyhf maintainer to expose a raw complex<int16_t> threadproc, or provide a way to switch the sample type in their existing threadproc. Converting to float and then back to integer seems truly wasteful, though I appreciate their desire to abstract away the underlying sample width. And since it appears there's no processing gain taking place, streaming floats over the network seems wasteful too. What do you think?

**Comment by jboone** [comment]
@f4exb Ha! I guess I should've looked at your other repos first. I see you've had similar thoughts, and acted on them already: https://github.com/f4exb/airspyhf/commits/intsamples

I will pull your airspyhf and update my code to use your modifications.

**Comment by f4exb** [comment]
Well actually I have come back on this and now rely on the original airspyhf library. At the sample rate of 768 kS/s the performance hit of having to convert from float to int is very minimal. This is a choice of the maintainer of airspyhf library to first convert to float in order to facilitate complex DSP processing in the later stages. 

Indeed the DC removal and IQ imbalance is done in the airspyhf library with a sophisticated algorithm taking into account the variation of IQ imbalance across the band that is being processed. In my opinion this is an overkill but I respect the choice. In the recent versions I think there is an option to bypass DSP processing. I have not implemented it yet in the SDRangel plugin.

**Comment by f4exb** [comment]
Superseded by https://github.com/f4exb/sdrangel/issues/196 
SDRangel supports 16 or 24 bit builds
SDRdaemon is going EOL

**Comment by f4exb** [comment]
Delivered in SDRangel v4.1.0
